name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Install GCC
        #run: sudo apt-get install gcc

      - name: Compile Hello World program
        run: gcc -o hello hello.c

      - name: Run Hello World program
        run: ./hello
